name: CI
on: [push, pull_request]

jobs:
  install:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Learner
        run: cd learner; ./install.sh
      - name: Install Mapper
        run: cd mapper; ./install.sh

  Linux_basic:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install TCP-Fuzzer
        run: ./install.sh
      - name: Test Ubuntu 24.04
        run: |
          ./run.sh -alphabet config/basic.xml -output output/ubuntu
          ./diff_hyps.sh experiments/models/linux-6.17.0_basic output/ubuntu 3
